In [1]:
#pip install tensorflow

In [2]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

categorical_data = ['cat', 'dog', 'cat', 'bird', 'dog']

categorical_data = np.array(categorical_data).reshape(-1, 1)

encoder = OneHotEncoder()

one_hot_encoded_data = encoder.fit_transform(categorical_data).toarray()
print("One Hot Encoded Data:")
print(one_hot_encoded_data)


One Hot Encoded Data:
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
